# Generated by Django 6.0.1 on 2026-03-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_prescription_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='diagnosis',
        ),
    ]
