# Generated by Django 6.0.1 on 2026-03-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_prescription_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
